cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'dart-lang/dart'
tap 'caskroom/fonts'
tap 'heroku/brew'

brew 'zsh'
brew 'zsh-completions'
brew 'openssl'
brew 'spaceman-diff'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'hub'
brew 'dart'
brew 'node'
brew 'npm'
brew 'watchman'
brew 'httpie'
brew 'heroku'

cask 'atom'
cask 'firefox'
cask 'slack'
cask 'vlc'
cask 'android-studio'
cask 'postman'
cask 'spotify'
cask 'iterm2'
cask 'istat-menus'
cask 'spectacle'
cask 'steam'
cask 'istat-menus'
cask 'flux'
cask 'font-fira-code'
cask 'graphql-playground'
cask 'keyboard-maestro'
cask 'aware'
cask 'quicklook-json'
cask 'realm-studio'
cask 'kap'
cask 'visual-studio-code'
